// DO NOT EDIT. generated by webtyp.com/ormc

package auth

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type User struct {
	Id string
	Email string
	Name string
	Phone string
	Status string
	Avatar string
	CreatedAt int64
}

func (m *User) ModelName() string { return "user" }

func (m *User) Schema() []model.Field { return UserModel.Fields }

func (m *User) Pointers() []any { return []any{&m.Id, &m.Email, &m.Name, &m.Phone, &m.Status, &m.Avatar, &m.CreatedAt} }

func (m *User) IsNil() bool { return m == nil }

func (m *User) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("email", m.Email)
	w.String("name", m.Name)
	w.String("phone", m.Phone)
	w.String("status", m.Status)
	w.String("avatar", m.Avatar)
	w.Int("created_at", m.CreatedAt)
}

func (m *User) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("phone"); ok { m.Phone = v }
	if v, ok := r.String("status"); ok { m.Status = v }
	if v, ok := r.String("avatar"); ok { m.Avatar = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = v }
}

type UserList []*User

func (s *UserList) Schema() []model.Field { return nil }
func (s *UserList) Pointers() []any     { return nil }
func (s *UserList) Len() int             { return len(*s) }
func (s *UserList) At(i int) model.Fielder { return (*s)[i] }
func (s *UserList) Append() model.Fielder  { v := &User{}; *s = append(*s, v); return v }
func (s *UserList) IsNil() bool          { return s == nil }
func (s *UserList) EncodeFields(_ model.FieldWriter) {}
func (s *UserList) DecodeFields(_ model.FieldReader) {}

func (m *User) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var User_ = struct {
	Id string
	Email string
	Name string
	Phone string
	Status string
	Avatar string
	CreatedAt string
}{
	Id: "id",
	Email: "email",
	Name: "name",
	Phone: "phone",
	Status: "status",
	Avatar: "avatar",
	CreatedAt: "created_at",
}

func ReadOneUser(qb *orm.QB, model *User) (*User, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUser(qb *orm.QB) (UserList, error) {
	var results UserList
	err := qb.ReadAll(
		func() model.Model { return &User{} },
		func(m model.Model) { results = append(results, m.(*User)) },
	)
	return results, err
}

type Session struct {
	Id string
	UserId string
	ExpiresAt int64
	Ip string
	UserAgent string
	CreatedAt int64
}

func (m *Session) ModelName() string { return "session" }

func (m *Session) Schema() []model.Field { return SessionModel.Fields }

func (m *Session) Pointers() []any { return []any{&m.Id, &m.UserId, &m.ExpiresAt, &m.Ip, &m.UserAgent, &m.CreatedAt} }

func (m *Session) IsNil() bool { return m == nil }

func (m *Session) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("user_id", m.UserId)
	w.Int("expires_at", m.ExpiresAt)
	w.String("ip", m.Ip)
	w.String("user_agent", m.UserAgent)
	w.Int("created_at", m.CreatedAt)
}

func (m *Session) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("user_id"); ok { m.UserId = v }
	if v, ok := r.Int("expires_at"); ok { m.ExpiresAt = v }
	if v, ok := r.String("ip"); ok { m.Ip = v }
	if v, ok := r.String("user_agent"); ok { m.UserAgent = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = v }
}

type SessionList []*Session

func (s *SessionList) Schema() []model.Field { return nil }
func (s *SessionList) Pointers() []any     { return nil }
func (s *SessionList) Len() int             { return len(*s) }
func (s *SessionList) At(i int) model.Fielder { return (*s)[i] }
func (s *SessionList) Append() model.Fielder  { v := &Session{}; *s = append(*s, v); return v }
func (s *SessionList) IsNil() bool          { return s == nil }
func (s *SessionList) EncodeFields(_ model.FieldWriter) {}
func (s *SessionList) DecodeFields(_ model.FieldReader) {}

func (m *Session) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Session_ = struct {
	Id string
	UserId string
	ExpiresAt string
	Ip string
	UserAgent string
	CreatedAt string
}{
	Id: "id",
	UserId: "user_id",
	ExpiresAt: "expires_at",
	Ip: "ip",
	UserAgent: "user_agent",
	CreatedAt: "created_at",
}

func ReadOneSession(qb *orm.QB, model *Session) (*Session, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllSession(qb *orm.QB) (SessionList, error) {
	var results SessionList
	err := qb.ReadAll(
		func() model.Model { return &Session{} },
		func(m model.Model) { results = append(results, m.(*Session)) },
	)
	return results, err
}

func (m *Session) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: SessionModel.Fields[1], Ref: "user", RefColumn: "id", OnDelete: ""},
	}
}

type Identity struct {
	Id string
	UserId string
	Provider string
	ProviderId string
	Email string
	CreatedAt int64
}

func (m *Identity) ModelName() string { return "identity" }

func (m *Identity) Schema() []model.Field { return IdentityModel.Fields }

func (m *Identity) Pointers() []any { return []any{&m.Id, &m.UserId, &m.Provider, &m.ProviderId, &m.Email, &m.CreatedAt} }

func (m *Identity) IsNil() bool { return m == nil }

func (m *Identity) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("user_id", m.UserId)
	w.String("provider", m.Provider)
	w.String("provider_id", m.ProviderId)
	w.String("email", m.Email)
	w.Int("created_at", m.CreatedAt)
}

func (m *Identity) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("user_id"); ok { m.UserId = v }
	if v, ok := r.String("provider"); ok { m.Provider = v }
	if v, ok := r.String("provider_id"); ok { m.ProviderId = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = v }
}

type IdentityList []*Identity

func (s *IdentityList) Schema() []model.Field { return nil }
func (s *IdentityList) Pointers() []any     { return nil }
func (s *IdentityList) Len() int             { return len(*s) }
func (s *IdentityList) At(i int) model.Fielder { return (*s)[i] }
func (s *IdentityList) Append() model.Fielder  { v := &Identity{}; *s = append(*s, v); return v }
func (s *IdentityList) IsNil() bool          { return s == nil }
func (s *IdentityList) EncodeFields(_ model.FieldWriter) {}
func (s *IdentityList) DecodeFields(_ model.FieldReader) {}

func (m *Identity) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Identity_ = struct {
	Id string
	UserId string
	Provider string
	ProviderId string
	Email string
	CreatedAt string
}{
	Id: "id",
	UserId: "user_id",
	Provider: "provider",
	ProviderId: "provider_id",
	Email: "email",
	CreatedAt: "created_at",
}

func ReadOneIdentity(qb *orm.QB, model *Identity) (*Identity, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllIdentity(qb *orm.QB) (IdentityList, error) {
	var results IdentityList
	err := qb.ReadAll(
		func() model.Model { return &Identity{} },
		func(m model.Model) { results = append(results, m.(*Identity)) },
	)
	return results, err
}

func (m *Identity) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: IdentityModel.Fields[1], Ref: "user", RefColumn: "id", OnDelete: ""},
	}
}

type LANIP struct {
	Id string
	UserId string
	Ip string
	Label string
	CreatedAt int64
}

func (m *LANIP) ModelName() string { return "lanip" }

func (m *LANIP) Schema() []model.Field { return LANIPModel.Fields }

func (m *LANIP) Pointers() []any { return []any{&m.Id, &m.UserId, &m.Ip, &m.Label, &m.CreatedAt} }

func (m *LANIP) IsNil() bool { return m == nil }

func (m *LANIP) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("user_id", m.UserId)
	w.String("ip", m.Ip)
	w.String("label", m.Label)
	w.Int("created_at", m.CreatedAt)
}

func (m *LANIP) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("user_id"); ok { m.UserId = v }
	if v, ok := r.String("ip"); ok { m.Ip = v }
	if v, ok := r.String("label"); ok { m.Label = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = v }
}

type LANIPList []*LANIP

func (s *LANIPList) Schema() []model.Field { return nil }
func (s *LANIPList) Pointers() []any     { return nil }
func (s *LANIPList) Len() int             { return len(*s) }
func (s *LANIPList) At(i int) model.Fielder { return (*s)[i] }
func (s *LANIPList) Append() model.Fielder  { v := &LANIP{}; *s = append(*s, v); return v }
func (s *LANIPList) IsNil() bool          { return s == nil }
func (s *LANIPList) EncodeFields(_ model.FieldWriter) {}
func (s *LANIPList) DecodeFields(_ model.FieldReader) {}

func (m *LANIP) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var LANIP_ = struct {
	Id string
	UserId string
	Ip string
	Label string
	CreatedAt string
}{
	Id: "id",
	UserId: "user_id",
	Ip: "ip",
	Label: "label",
	CreatedAt: "created_at",
}

func ReadOneLANIP(qb *orm.QB, model *LANIP) (*LANIP, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllLANIP(qb *orm.QB) (LANIPList, error) {
	var results LANIPList
	err := qb.ReadAll(
		func() model.Model { return &LANIP{} },
		func(m model.Model) { results = append(results, m.(*LANIP)) },
	)
	return results, err
}

func (m *LANIP) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: LANIPModel.Fields[1], Ref: "user", RefColumn: "id", OnDelete: ""},
	}
}

type OAuthState struct {
	State string
	NonceHash string
	Provider string
	ExpiresAt int64
	CreatedAt int64
}

func (m *OAuthState) ModelName() string { return "oauth_state" }

func (m *OAuthState) Schema() []model.Field { return OAuthStateModel.Fields }

func (m *OAuthState) Pointers() []any { return []any{&m.State, &m.NonceHash, &m.Provider, &m.ExpiresAt, &m.CreatedAt} }

func (m *OAuthState) IsNil() bool { return m == nil }

func (m *OAuthState) EncodeFields(w model.FieldWriter) {
	w.String("state", m.State)
	w.String("nonce_hash", m.NonceHash)
	w.String("provider", m.Provider)
	w.Int("expires_at", m.ExpiresAt)
	w.Int("created_at", m.CreatedAt)
}

func (m *OAuthState) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("state"); ok { m.State = v }
	if v, ok := r.String("nonce_hash"); ok { m.NonceHash = v }
	if v, ok := r.String("provider"); ok { m.Provider = v }
	if v, ok := r.Int("expires_at"); ok { m.ExpiresAt = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = v }
}

type OAuthStateList []*OAuthState

func (s *OAuthStateList) Schema() []model.Field { return nil }
func (s *OAuthStateList) Pointers() []any     { return nil }
func (s *OAuthStateList) Len() int             { return len(*s) }
func (s *OAuthStateList) At(i int) model.Fielder { return (*s)[i] }
func (s *OAuthStateList) Append() model.Fielder  { v := &OAuthState{}; *s = append(*s, v); return v }
func (s *OAuthStateList) IsNil() bool          { return s == nil }
func (s *OAuthStateList) EncodeFields(_ model.FieldWriter) {}
func (s *OAuthStateList) DecodeFields(_ model.FieldReader) {}

func (m *OAuthState) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var OAuthState_ = struct {
	State string
	NonceHash string
	Provider string
	ExpiresAt string
	CreatedAt string
}{
	State: "state",
	NonceHash: "nonce_hash",
	Provider: "provider",
	ExpiresAt: "expires_at",
	CreatedAt: "created_at",
}

func ReadOneOAuthState(qb *orm.QB, model *OAuthState) (*OAuthState, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllOAuthState(qb *orm.QB) (OAuthStateList, error) {
	var results OAuthStateList
	err := qb.ReadAll(
		func() model.Model { return &OAuthState{} },
		func(m model.Model) { results = append(results, m.(*OAuthState)) },
	)
	return results, err
}

type LoginData struct {
	Email string
	Password string
}

func (m *LoginData) ModelName() string { return "login_data" }

func (m *LoginData) Schema() []model.Field { return LoginDataModel.Fields }

func (m *LoginData) Pointers() []any { return []any{&m.Email, &m.Password} }

func (m *LoginData) IsNil() bool { return m == nil }

func (m *LoginData) EncodeFields(w model.FieldWriter) {
	w.String("email", m.Email)
	w.String("password", m.Password)
}

func (m *LoginData) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("password"); ok { m.Password = v }
}

type LoginDataList []*LoginData

func (s *LoginDataList) Schema() []model.Field { return nil }
func (s *LoginDataList) Pointers() []any     { return nil }
func (s *LoginDataList) Len() int             { return len(*s) }
func (s *LoginDataList) At(i int) model.Fielder { return (*s)[i] }
func (s *LoginDataList) Append() model.Fielder  { v := &LoginData{}; *s = append(*s, v); return v }
func (s *LoginDataList) IsNil() bool          { return s == nil }
func (s *LoginDataList) EncodeFields(_ model.FieldWriter) {}
func (s *LoginDataList) DecodeFields(_ model.FieldReader) {}

func (m *LoginData) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type RegisterData struct {
	Name string
	Email string
	Password string
	Phone string
}

func (m *RegisterData) ModelName() string { return "register_data" }

func (m *RegisterData) Schema() []model.Field { return RegisterDataModel.Fields }

func (m *RegisterData) Pointers() []any { return []any{&m.Name, &m.Email, &m.Password, &m.Phone} }

func (m *RegisterData) IsNil() bool { return m == nil }

func (m *RegisterData) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.String("email", m.Email)
	w.String("password", m.Password)
	w.String("phone", m.Phone)
}

func (m *RegisterData) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("password"); ok { m.Password = v }
	if v, ok := r.String("phone"); ok { m.Phone = v }
}

type RegisterDataList []*RegisterData

func (s *RegisterDataList) Schema() []model.Field { return nil }
func (s *RegisterDataList) Pointers() []any     { return nil }
func (s *RegisterDataList) Len() int             { return len(*s) }
func (s *RegisterDataList) At(i int) model.Fielder { return (*s)[i] }
func (s *RegisterDataList) Append() model.Fielder  { v := &RegisterData{}; *s = append(*s, v); return v }
func (s *RegisterDataList) IsNil() bool          { return s == nil }
func (s *RegisterDataList) EncodeFields(_ model.FieldWriter) {}
func (s *RegisterDataList) DecodeFields(_ model.FieldReader) {}

func (m *RegisterData) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ProfileData struct {
	Name string
	Phone string
}

func (m *ProfileData) ModelName() string { return "profile_data" }

func (m *ProfileData) Schema() []model.Field { return ProfileDataModel.Fields }

func (m *ProfileData) Pointers() []any { return []any{&m.Name, &m.Phone} }

func (m *ProfileData) IsNil() bool { return m == nil }

func (m *ProfileData) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.String("phone", m.Phone)
}

func (m *ProfileData) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("phone"); ok { m.Phone = v }
}

type ProfileDataList []*ProfileData

func (s *ProfileDataList) Schema() []model.Field { return nil }
func (s *ProfileDataList) Pointers() []any     { return nil }
func (s *ProfileDataList) Len() int             { return len(*s) }
func (s *ProfileDataList) At(i int) model.Fielder { return (*s)[i] }
func (s *ProfileDataList) Append() model.Fielder  { v := &ProfileData{}; *s = append(*s, v); return v }
func (s *ProfileDataList) IsNil() bool          { return s == nil }
func (s *ProfileDataList) EncodeFields(_ model.FieldWriter) {}
func (s *ProfileDataList) DecodeFields(_ model.FieldReader) {}

func (m *ProfileData) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type PasswordData struct {
	Current string
	New string
	Confirm string
}

func (m *PasswordData) ModelName() string { return "password_data" }

func (m *PasswordData) Schema() []model.Field { return PasswordDataModel.Fields }

func (m *PasswordData) Pointers() []any { return []any{&m.Current, &m.New, &m.Confirm} }

func (m *PasswordData) IsNil() bool { return m == nil }

func (m *PasswordData) EncodeFields(w model.FieldWriter) {
	w.String("current", m.Current)
	w.String("new", m.New)
	w.String("confirm", m.Confirm)
}

func (m *PasswordData) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("current"); ok { m.Current = v }
	if v, ok := r.String("new"); ok { m.New = v }
	if v, ok := r.String("confirm"); ok { m.Confirm = v }
}

type PasswordDataList []*PasswordData

func (s *PasswordDataList) Schema() []model.Field { return nil }
func (s *PasswordDataList) Pointers() []any     { return nil }
func (s *PasswordDataList) Len() int             { return len(*s) }
func (s *PasswordDataList) At(i int) model.Fielder { return (*s)[i] }
func (s *PasswordDataList) Append() model.Fielder  { v := &PasswordData{}; *s = append(*s, v); return v }
func (s *PasswordDataList) IsNil() bool          { return s == nil }
func (s *PasswordDataList) EncodeFields(_ model.FieldWriter) {}
func (s *PasswordDataList) DecodeFields(_ model.FieldReader) {}

func (m *PasswordData) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

